# ∀lacirrty config 23 August

# ---

# General thingys
[general]

# # Importar cosas
# import = [
#]

# Cambiar el directory que aparece
working_directory = "None"

# Recargar en hot
live_config_reload = true

# 
ipc_socket = true

# ---

# Environment thingys
[env]

# ---

# Window
[window]

# Dimensiones (cambios requieren que se reinicie)
dimensions = { columns = 0, lines = 0 }

# No tiene efecto en wayland (posición de la cosa)
position = "None"

# Padding
padding = { x = 8, y = 8 }

# Padding Dynamic~
dynamic_padding = false

# Decoraciones ( muchas solo sirven en mierdaOS) (solo funcionan Full o None en xorg por lo que he visto jeje.)
# En cambio si sos de MacMierda: Transparent y Buttonless
decorations = "Full"

# Opacidad
opacity = 0.8910


# Blur (works on mierdaOS y KDE wayland al parecer)
blur = true

# # Coso de iniciar
# startup_mode = "Windowed"

# Cambiar el título, rey
title = "∀lacirrty"

# Título dynamic~
dynamic_title = true

# Class
class = { instance = "∀lacirrty", general = "∀lacirrty" }

# Tema Dark Light y None (para el tema default)
decorations_theme_variant = "None"

# Al parecer funciona en todos jasdkfljasdf
resize_increments = true

# Hacer que option key sea como alt
option_as_alt = "None"

# Nivel AlwaysOnTop Normal
level = "Normal"

# ---

# Scrolling
[scrolling]

# Historial
history = 10000

# number of line skipped by coso de ir arriba o abajo
multiplier = 3

# ---

# Font
[font]

# Normal
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

# bold
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }

# italic
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }

# Bold & italic
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

# font zise
size = 5.67

# offset
offset = { x = 0, y = 0 }

# glypho
glyph_offset = { x = 0, y = 0 }

# When true, Alacritty will use a custom built-in font for box drawing characters (Unicode points U+2500 - U+259F), legacy computing symbols (U+1FB00 - U+1FB3B), and powerline symbols (U+E0B0 - U+E0B3).
builtin_box_drawing = true

# ---

# Colors (i'm not doing that allat)

# ---

# Bell

# idk

# ---

# Selection
[selection]

# default
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

# default is false
save_to_clipboard = true

# ---

# Cursor
[cursor]

# style
style = { shape = "Block", blinking = "On" }

# ---

# Terminal

# ---

# Mouse

# ---

# Hints

# ---

# Keyboard
[keyboard]

# bindings = [
# {  },
# ]

# ---
